### ISSUE TITLE
Are ipywidgets enabled?

### ISSUE THREAD

**Issue by ericmjl** [QuantStack/voila#15] opened 2018-11-15 14:02 UTC
I have a notebook in which I use ipywidgets to update a plot. Is this supported with voila? It appears that the widget that I use doesn't show up when served by `voila`.

Btw, this looks very close to the exact thing that I was looking for, to serve up a notebook for my colleagues who aren't programming-savvy! Thank you for making this!

**Comment by maartenbreddels** [comment] 2018-11-15 14:09
Hi Eric,

Thanks for your feedback! Yes, the widgets should work. What widget is it that is not working? Did you test that the core ipywidgets are working, like a FloatSlider for instance?

cheers.

Maarten

**Comment by ericmjl** [comment] 2018-11-15 14:14
Thank you for getting back, @maartenbreddels! 

The widget that isn't working for me right now is the Dropdown widget. It appears the Progress Bar widget is working fine (I am using `tqdm_notebook` inside the notebook).

**Comment by SylvainCorlay** [comment] 2018-11-15 14:17
Is there any error showing up on the JS side with the browser console?

**Comment by ericmjl** [comment] 2018-11-15 14:20
@SylvainCorlay thank you also for responding! I do not see any errors related to widgets in the JS console in my browser, though I do see one related to a favicon. It apparently shouldn't be the issue, I guess.

Screenshot available below:

<img width="652" alt="screen shot 2018-11-15 at 9 19 48 am" src="https://user-images.githubusercontent.com/2631566/48558598-aa61de80-e8b7-11e8-8dd2-9fd4d7d6a113.png">

**Comment by ericmjl** [comment] 2018-11-15 14:29
@SylvainCorlay @maartenbreddels I tried switching my dropdown to an IntSlider, and that apparently is not working either.

Perhaps it might be the way I am calling on the widget? I am using the following pattern:

```python
dropdown = Dropdown(options=...)

@interact(arg=dropdown)
def func(arg):
   ...
    plt.plot(...)
```

I created a minimal example that reproduces the problem, below. Apologies for the lack of code the first time round, I was working with code that dealt with company data.

```python
from ipywidgets import Dropdown, interact, fixed
import matplotlib.pyplot as plt
import numpy as np

%load_ext autoreload
%autoreload 2
%matplotlib inline
%config InlineBackend.figure_format = 'retina'

x = np.linspace(-10, 10, 1000)

@interact(A=range(10), x=fixed(x))
def plot(A, x):
    plt.plot(A * np.sin(x))
```

When served with voila, I see the following in my browser:

<img width="1175" alt="screen shot 2018-11-15 at 9 29 03 am" src="https://user-images.githubusercontent.com/2631566/48559113-efd2db80-e8b8-11e8-8918-cb5a88fbb7ae.png">

**Comment by SylvainCorlay** [comment] 2018-11-15 14:31
Ah, I think that the issue is that you are using `interact`. I don't think that voila's implementation of the output widget works quite yet.

**Comment by SylvainCorlay** [comment] 2018-11-20 09:40
Closing and opening a specific issue about the output widgets and interact support.

**Closed by SylvainCorlay** 2018-11-20 09:40 UTC

**Comment by andymbryant** [comment] 2020-05-29 14:56
If anyone else is coming here from Google because their matplotlib plot(s) are empty, be sure to add: `import ipympl` to the file and add `plt.show()` to each cell with a plot in it.
