### ISSUE TITLE
500 : Internal Server Error

### ISSUE THREAD

**Issue by m-albert** [QuantStack/voila#313] opened 2019-07-19 13:54 UTC
I'm getting this error, even after updating pygments.

> ~/misc_notebooks$ voila test.ipynb
> [Voila] Using /tmp to store connection files
> [Voila] Storing connection files in /tmp/voila_f3lul4ru.
> [Voila] Serving static files from /home/malbert/miniconda3/envs/voila/lib/python3.7/site-packages/voila/static.
> [Voila] Voila is running at:
> http://localhost:8866/
> [Voila] WARNING | No web browser found: could not locate runnable browser.
> [Voila] WARNING | Notebook cake_fusion_function.ipynb is not trusted
> [Voila] Kernel started: e8018fad-8a34-4b2d-a8f6-0d97d04ce0aa
> [Voila] Executing notebook with kernel:
> ERROR:tornado.application:Uncaught exception GET / (10.11.63.205)
> HTTPServerRequest(protocol='http', host='elvis:8866', method='GET', uri='/', version='HTTP/1.1', remote_ip='10.11.63.205')
> Traceback (most recent call last):
> File "/home/malbert/miniconda3/envs/voila/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
> result = await result
> File "/home/malbert/miniconda3/envs/voila/lib/python3.7/site-packages/tornado/gen.py", line 748, in run
> yielded = self.gen.send(value)
> File "/home/malbert/miniconda3/envs/voila/lib/python3.7/site-packages/voila/handler.py", line 60, in get
> result = executenb(notebook, km=km, cwd=cwd)
> File "/home/malbert/miniconda3/envs/voila/lib/python3.7/site-packages/voila/execute.py", line 133, in executenb
> return ep.preprocess(nb, resources, km=km)[0]
> File "/home/malbert/miniconda3/envs/voila/lib/python3.7/site-packages/voila/execute.py", line 88, in preprocess
> result = super(ExecutePreprocessorWithOutputWidget, self).preprocess(nb, resources=resources, km=km)
> File "/home/malbert/miniconda3/envs/voila/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 381, in preprocess
> nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
> File "/home/malbert/miniconda3/envs/voila/lib/python3.7/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
> nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
> File "/home/malbert/miniconda3/envs/voila/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 414, in preprocess_cell
> reply, outputs = self.run_cell(cell, cell_index)
> File "/home/malbert/miniconda3/envs/voila/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 516, in run_cell
> self.process_message(msg, cell, cell_index)
> File "/home/malbert/miniconda3/envs/voila/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 569, in process_message
> self.handle_comm_msg(cell.outputs, msg, cell_index)
> File "/home/malbert/miniconda3/envs/voila/lib/python3.7/site-packages/voila/execute.py", line 107, in handle_comm_msg
> state = data['state']
> KeyError: 'state'
> ERROR:tornado.general:Could not open static file '/base/images/favicon.ico'
> ERROR:tornado.general:Could not open static file '/style/style.min.css'
> ERROR:tornado.access:500 GET / (10.11.63.205) 1356.58ms

output of pip list:

> attrs 19.1.0
> backcall 0.1.0
> bleach 3.1.0
> certifi 2019.6.16
> cycler 0.10.0
> decorator 4.4.0
> defusedxml 0.5.0
> entrypoints 0.3
> ipykernel 5.1.1
> ipython 7.6.1
> ipython-genutils 0.2.0
> jedi 0.14.1
> Jinja2 2.10.1
> jsonschema 3.0.1
> jupyter-client 5.3.1
> jupyter-core 4.4.0
> jupyter-server 0.0.5
> jupyterlab-pygments 0.1.0
> kiwisolver 1.1.0
> MarkupSafe 1.1.1
> matplotlib 3.1.0
> mistune 0.8.4
> mkl-fft 1.0.12
> mkl-random 1.0.2
> nbconvert 5.5.0
> nbformat 4.4.0
> numpy 1.16.4
> pandocfilters 1.4.2
> parso 0.5.1
> pexpect 4.7.0
> pickleshare 0.7.5
> pip 19.1.1
> prometheus-client 0.7.1
> prompt-toolkit 2.0.9
> ptyprocess 0.6.0
> Pygments 2.4.2
> pyparsing 2.4.0
> pyrsistent 0.15.3
> python-dateutil 2.8.0
> pytz 2019.1
> pyzmq 18.0.2
> scipy 1.2.1
> Send2Trash 1.5.0
> setuptools 41.0.1
> six 1.12.0
> terminado 0.8.2
> testpath 0.4.2
> tornado 6.0.3
> traitlets 4.3.2
> voila 0.1.7
> wcwidth 0.1.7
> webencodings 0.5.1
> wheel 0.33.4

Thanks for any hints!

**Comment by maartenbreddels** [comment] 2019-07-24 07:57
I think this is a duplicate of https://github.com/QuantStack/voila/issues/311
If you could share your notebook, that would be great!

**Closed** 2019-07-24 10:31 UTC
